version: '3.1'
services:
  stat_svc:
    build: ./stat_svc/stat-service
    image: stat-svc-image
    container_name: emv-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - URL=jdbc:postgresql://ewm-stats-db:5432/ewm
      - POSTGRES_USER=andr
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    build:
      context: ./
      dockerfile: ./Dockerfile.postgres
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=andr
      - POSTGRES_PASSWORD=root
