drop table IF EXISTS hits CASCADE;

CREATE TABLE IF NOT EXISTS hits (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app VARCHAR NOT NULL,
    uri VARCHAR NOT NULL,
    ip VARCHAR NOT NULL,
    time_from_request TIMESTAMP WITHOUT TIME ZONE
    );