drop table IF EXISTS apps CASCADE;
drop table IF EXISTS hits CASCADE;

CREATE TABLE IF NOT EXISTS apps (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   app_name VARCHAR NOT NULL,
   CONSTRAINT pk_apps PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id INTEGER NOT NULL,
    uri VARCHAR NOT NULL,
    ip VARCHAR NOT NULL,
    time_from_request TIMESTAMP WITHOUT TIME ZONE,
    constraint APP_ID_FK_HITS foreign key (app_id) references apps(id)
    );

